### ISSUE TITLE
Betrayed Bonds

### ISSUE THREAD

**Issue by ghost** [MrZhang365/MrZhang365#1]
After years of building our friendship, you chose to erase it without a second thought.

Your decision to unfollow me has not only hurt me deeply but also filled me with anger. The trust I placed in you has been brutally betrayed, leaving me grappling with a profound sense of loss and disappointment.

**Comment by MrZhang365** [comment]
Are you sure we have several years of friendship? It seems like we haven't been in touch anymore except for chatting on HackChat that day and recently on GitHub.
